### ISSUE TITLE
Ugly border

### ISSUE THREAD

**Issue by SleipRecx** [NTNUIKoiene/koieneres-frontend#54]
![bug](https://user-images.githubusercontent.com/11886100/53792298-9c4dd180-3f2b-11e9-9b99-0cc23b9d9da5.png)

**Comment by espenmeidell** [comment]
Which os / browser combination? Does not appear to be a problem on firefox or chrome on Ubuntu

**Comment by SleipRecx** [comment]
OSX and Chrome. Probably caused by limited screen width on 13 inch

**Comment by SleipRecx** [comment]
Also on Ubuntu Firefox, I think it's caused by the question mark button.
