### ISSUE TITLE
Add eslint-plugin-react-hooks 

### ISSUE THREAD

**Issue by SleipRecx** [NTNUIKoiene/koieneres-frontend#81]
Add and configure `eslint-plugin-react-hooks `
[https://reactjs.org/docs/hooks-rules.html](https://reactjs.org/docs/hooks-rules.html)

**Comment by espenmeidell** [comment]
Should not be used with create-react-app (https://www.npmjs.com/package/eslint-plugin-react-hooks). Must wait for new release of react-scripts

**Comment by SleipRecx** [comment]
Will be available in v3.0 of create-react-app, progress is tracked [here.](https://github.com/facebook/create-react-app/milestone/58)
